### ISSUE TITLE
error when creating a python class inheriting from a ROOT class,  6.22/02

### ISSUE THREAD

**Issue by ThomasRuf** [root-project/root#6856]
Example with TH1F, for reproducibility,  but happens for any class accessed via ROOT.

>>> class MyClass(ROOT.TH1F):
...    "My Class"
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'UpdateBinContent'

The variable with the KeyError is always the variable last in the list of private data members. 
This error appears on lxplus, CentOS Linux 7 (Core), gcc version  7.3.0,  CXXFLAGS=-fPIC -g -O2 -std=c++17

This error DOES NOT appear on Ubuntu 20.04.1 LTS, gcc version 9.3.0.

**Comment by eguiraud** [comment]
Hi,
thank you for the report.

> This error DOES NOT appear on Ubuntu 20.04.1 LTS, gcc version 9.3.0.

Is the ROOT version on Ubuntu 20.04 still 6.22/02?

I could not reproduce this with a ROOT v6.22/02 installed via conda or in a couple of different LCG releases that I tried out on LXPLUS. Could you provide a recipe to reproduce this on our side (e.g. on LXPLUS)?

Could this issue be an instance of https://sft.its.cern.ch/jira/browse/ROOT-11025 (fixed in master and 6.22/04)? If yes, could you please check whether it is fixed in ROOT's [nightly builds](https://root.cern/install/nightlies/)?

Cheers,
Enrico

**Comment by ThomasRuf** [comment]
Thanks for the fast response. The issue 11025 is definitely the same that I observe. The last variable in the list of protected variables is TSelectorList *fOutput;. Same signature as my issue. Concerning Ubuntu, yes, it is the same ROOT version, but different compiler. I will download 6.22/04 and compile. Using the nightly build does not work,  source /cvmfs/sft.cern.ch/lcg/views/dev3python3/latest/x86_64-slc6-gcc7-opt/setup.sh 
python
import ROOT
ModuleNotFoundError: No module named 'ROOT'

**Comment by olantwin** [comment]
For the nightly version, could you try using `python3` rather than `python`? `python` probably points to `python2`.

**Comment by ThomasRuf** [comment]
python3
Python 3.6.5 (default, Jun 15 2019, 23:43:07) 
[GCC 7.3.0] on linux
>>> import ROOT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ROOT'

typing root:
/usr/bin/root.exe: /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3python3/Thu/x86_64-slc6-gcc7-opt/lib/liblzma.so.5: no version information available (required by /usr/lib64/root/libCore.so.6.22)
   ------------------------------------------------------------------
  | Welcome to ROOT 6.22/02                        https://root.cern |
....

**Comment by olantwin** [comment]
Ah, I think I see the problem: You are sourcing the slc6 version. Could you try again with the cc7 version?

**Comment by ThomasRuf** [comment]
not much better:
source /cvmfs/sft.cern.ch/lcg/views/dev3python3/latest/x86_64-centos7-gcc7-opt/setup.sh 
python3
Python 3.6.8 (default, Oct 13 2020, 16:18:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux   ????
import ROOT
  ROOT.__file__
'/usr/lib64/python3.6/site-packages/ROOT/__init__.py'

not what I want.

**Comment by eguiraud** [comment]
mmmh yep that should not happen, I'm trying to figure out what's wrong with the LCG nightlies -- sorry about that.

In the meanwhile: if this issue is indeed an instance of https://sft.its.cern.ch/jira/browse/ROOT-11025 , it should be fixed in master and 6.22/04.
Indeed `source /cvmfs/sft.cern.ch/lcg/views/LCG_98apython3/x86_64-centos7-gcc8-opt/setup.sh` (6.22/04) seems to work fine on lxplus, but on the other hand I was never able to reproduce the problem...

**Comment by olantwin** [comment]
Maybe an issue with the gcc7 version on LCG? Loading the nightlies with gcc10 works as well.

The issue seems fixed there, but I'll let Thomas confirm.

@eguiraud I saw there is a major issue with 6.22/04? Is this fixed or should we wait for 6.22/06? (we can easily pin any commit or tag, so don't necessarily need to stick to a given release).

**Comment by eguiraud** [comment]
That's correct, we can use 6.22/04 to check if the issue is fixed but don't stick with it, 6.22/06 is coming very soon.

**Comment by ThomasRuf** [comment]
OK, checked out ROOT master, 8a31480012b2a94d19062ebccead1c4337839c85, and this problem disappeared. 

But a news issue comes up when compiling our software, to be discussed in another thread, return type 'class TString' is incomplete.

And by the way, the problem with TPythia8 is still present, https://sft.its.cern.ch/jira/browse/ROOT-10895.

**Comment by eguiraud** [comment]
@ThomasRuf ROOT-10895 is indeed still in the works. Please open a new thread with a recipe to reproduce the issue regarding the problem with `return type 'class TString'`.

Marking this one as solved in 6.22/04 and master. Thank you for your collaboration!
