### ISSUE TITLE
Fix grammar and typos in Tree Chapter of User's Guide

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#7284]
Today I read User's Guide and spotted many mistakes I noticed when reading it for the first time 15 years ago. I thought that now is the time for me to act and to finally fix them.
I'm not a native speaker, so I don't insist on all of them (I still doubt the usage of articles when I write this small report).

If it's really easier for you, the next time I can try to make a push release with the corrections.

The good thing that I noted is that there are some fixes in the recent html pages compared to the pdf User's Guide of 2018, so I refer to this page when I cite the mistakes:
https://root.cern/root/htmldoc/guides/users-guide/Trees.html

14.3
is the use the TTree::Show method
\- to use
14.4
the branches and the leaves, is TTree::Print.
\- no need for a comma
14.6
boxes".
\- no need for the quote.
witch is marked
\- which is marked
exposed expression
\- I think that would sound better as "set expression" or another adjective.
Below them there are two text widgets
\- possible, but I think 'there' is redundant here.
for specifying
\- to specify
\-\- I think this text should be checked by a native speaker for articles and other issues.
When the “Rec” box is checked, the Draw and Scan commands
\- no need for quotes around Rec (or add them around Draw and Scan)
14.7
This picture shows the TTree class:
\- should be rewritten with a reference to the picture. On the pdf manual the picture is on a separate page, away from this line!
14.7.3
save all branch buffers every n byte.
\- bytes.
14.7.4
When a TTree is memory resident, you set it up so that it retains retain only the last few entries.
\- retains
For example, this can be very useful for monitoring purpose.
\- just for monitoring, remove 'purpose'. Maybe rewrite this phrase.
14.7.6
The function TTree::GetUserInfo() allows adding any object defined by a user to the tree that is not depending on the entry number.
\- allows to add to the tree any user\-defined object that doesn't depend on...

(actually didn't read the complete Chapter)

14.23
The performance depends not only of the processor type, but also of the disk devices (local, NFS, AFS, etc.).
\- Performance depends not only on the processor type, but also on storage devices (local, NFS, AFS, etc.).

**Comment by ynikitenko** [comment]
Several new corrections since last evening

14.14.3.1
// the objrect event has been filled at this point
\- object
We want to keep the generated
// histograms we open a browser and the TreeViewer
\- when we open
14.15.2
In this analysis, we do not read the entire entry we only read one branch.
\- entry,
(see Trees in Analysis).
\- should be a link.
// we are only interested by the destep branch
\- "interested in" is much more common, https://english.stackexchange.com/a/226731/116650
14.20.7.1
46
an histogram
\- a histogram. This word is normally pronounced with a consonant 'h' in the beginning.
47
You can plot plot objects of any class which
\- plot... that
14.20.8.1
They use the human ability to spot un-symmetry.
\- asymmetry (a distinction that produces such a lack of symmetry, see Wiktionary)
Example of spider plot.
\- of a
with the spider plots’ output
\- plot's
to navigate in the tree.
\- to navigate the tree.
14.20.8.2
The Parallel Coordinates representation of the six dimensional point
\- of a six-dimensional (https://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0117.html, https://forum.wordreference.com/threads/spelling-three-dimensional-vs-multidimensional.695071/)
14.20.9
TTree::Scan can be used to print the content of the tree’s entries optional passing a selection.
\- , optionally
will print all the variable of the tree.
\- all variables
Specific variables of the tree can be explicit selected by list them in column separated list:
\- explicitly ... by listing them ... in a column-separated (this is a compound word, cf. https://en.wikipedia.org/wiki/Comma-separated_values, https://www.ef.com/wwen/english-resources/english-grammar/hyphens-and-dashes/, https://english.stackexchange.com/questions/889/when-should-com-pound-words-be-writ-ten-as-one-word-with-hy-phens-or-with-spac)
will results in a printing similar to:
\- will result in output similar to:
can be use to specific the layout of the table:
\- to specify
all the column. If this options is not
\- all columns. If this option...
14.20.10
The TTree::Drawmethod can also be used to build a list of the entries.
\- of entries.
14.24.1
The number of entries in the friend must be equal or greater to the number of entries of the original chain.
\- equal to or greater than the number...

**Comment by ynikitenko** [comment]
14.10.1.2
See "
Performance Benchmarks"
\- redundant newline
14.10.2
If you are creating a branch with an object and in general you want the data members to be split, but you want to exempt a data member from the split. You can specify this in the comment field of the data member:
\- When you create a branch with an object, in general you want the data members to be split. But if you want to exempt a data member from the split, you can specify this in the comment field of the data member:
14.12
the entry in the collection becomes in turn top level branches, etc.
\- a top level branch
IMPORTANT NOTE1: This function should not be called if splitlevel<1. IMPORTANT NOTE2:
\- reconsider formatting.
14.14.1.1 Creating Branches with A single Variable
\- a single variable
14.14.1.2
the number of existing entries is null.
\- is zero.

**Comment by couet** [comment]
May I suggest that, instead of creating an issue, you do a Pull Request on the source file: https://github.com/root-project/root/blob/master/documentation/users-guide/Trees.md ?

**Comment by couet** [comment]
Note also we have now a new "Manual" online: https://root.cern/manual/trees/

**Comment by ynikitenko** [comment]
Yes, I noted that, but it looks like it's a shorter version of that in the User's Guide. I hope "new" doesn't mean that it will replace the existing manual (or, even worse, to create a second source of the same documentation)?

**Comment by ynikitenko** [comment]
@couet - ok, next time I'll try to make a Pull Request! An issue seems a bit more interactive though (I don't do PRs often).

**Comment by couet** [comment]
PR are very Interactives too. But we discuss over the mods and once finalise we commit. I suggest that you do a PR with all the list of mods you suggest here.

**Comment by couet** [comment]
The User's will not be update in the future. It is not referenced form the new web site. The base of the Doc is the Reference Guide now and the Manual Is an overview helping to navigate into it. Se the explanation here: https://root.cern/manual/

**Comment by ynikitenko** [comment]
1) Fine, I'll try a PR next time. However, since I already published in issue here, maybe someone will fix that (there is an assignee chosen).
2) I found the User's Guide more comprehensive, but I'll try the Manual as well. I can't find a pdf version of the manual on its page, is there any?

**Comment by couet** [comment]
As I said we do not spend time on the users guide now. The .md files are still there though. So if someone is willing to do a valid PR on them we will considered it and merge it when finalised. So please convert this into is PR. And, once again, the User's guide is now frozen and not updated. It has never been update by the way. After the first writing developers did not put any new stuff in it. We found out that developers put the doc in the code. That why we choose doxygen which allow to produce the reference guide. Having a separated  User's Guide often implies to duplicate the information with the risk of not being in sync. But we still need an entry point for people starting with ROOT. That is why we made the "Manual" which is still under development. The Manual has a much higher view that the reference Guide and helps to navigate into it. But it does not duplicate the information !! that's the key ! ... also, for beginners, we have the Primer also referenced from the web site.

**Comment by ynikitenko** [comment]
Ok, thanks for the explanations. I started to use ROOT near 2005, and I mostly used the User's Guide since then (sometimes consulting Class Reference).

I found that there is probably no Manual in pdf (or other format for downloading), which is a pity. I'm not sure whether I shall make a separate improvement issue about that (I already made several ones).

I also think that if it's decided that the User's Guide will no longer be used, its .md files should be deleted from active repository (and remain in old versions, if one really needs them). Its links should be removed from the site (and the old site should probably removed as well), and it should be stated that that User's Guide is outdated. Otherwise it would lead to confusion (among those who used the User's Guide) and desynchronization (though most API I see in the manual remains pretty the same).

**Comment by couet** [comment]
We are not in a development phase and some information still need to be moved form the old structure to the new one. That's why we keep for now the old informations. But hopefully if you do a consistent navigation starting from the new web site it should be consistent.  We made this changes mainly because the old sham did not scale with the fast growing of ROOT. So if you agree we can close this issue.

**Comment by ynikitenko** [comment]
You probably mean "are now in development phase".
As of today, I see that 
1) there is no better document than the User's guide (the chapter about trees there looks more comprehensive to me than in the manual).
2) it is still available from the site, people may use that. 
3) the manual has no pdf. For me it's very important, because I don't want to be online to read docs. I could use `wget`, but when I have a ready pdf, I chose the latter.

I honestly think that User's Guide is well-written and useful. I think that to do small updates to that (at least to sync the pdf version with html) are better now until the manual is finalized and definitely better than the old guide.

**Comment by couet** [comment]
Yes I made a typo. It is fixed now.

The full information about TTree should be in the Reference Guide. We will not update the User's guide any more. It could be useful if you point stuff you find in the User's Guide but not in the Reference or in the Manual. That would help us to update both. By the way: Try to find something about RDataFrame in the user's Guide.

**Comment by ynikitenko** [comment]
I don't need the full information. I needed information to learn about the topic. A good book is not only an information container, but it teaches ideas. 

I think that if manual creators know what and how to write, they can look at the existing docs (or skip outdated data from there). 

If you don't plan to update the User's guide, there is probably no need to fix that with Push Releases.

As I understand, you wrote that rdataframe is missing in the manual, so I won't find out there. Anyway I don't use that.

**Comment by couet** [comment]
Yes we are working on the manual. And please if you see something missing in Manual or in the reference guide which is no where else but in the Old User's Guide, let us know and we will make sure it appears somewhere. 
I guess we can close this issue now ?

**Comment by ynikitenko** [comment]
Fine, I'll open a ticket if I find something in the User's Guide missing in the Manual (or the reference guide).

For me this issue is not resolved in this state of things. I would rather simply fix that. However, if your workflow says that you can close that, you can do that - it's your project and your decisions.

**Comment by couet** [comment]
As I said if you want to make a PR against the tree.md with this changes I will look at it and apply it.

**Comment by ynikitenko** [comment]
I don't understand what would be the use of corrections if no one is going to compile a new PDF, and it is to be removed from the site?

**Comment by couet** [comment]
Yes, right. Don't do it in that case.
